application:
  key: ${api.key}
  file-path: /data
  file-name: file

server:
 ssl:
   enabled: true
   key-store: classpath:keystore.p12
   key-store-password: changeit
   key-password: changeit
   key-alias: keystore
 port: 8443
 compression:
   enabled: true
   min-response-size: 1KB

logging:
  level:
    com.dodecaedro: INFO

spring:
  main:
    lazy-initialization: true
